#!/usr/bin/env bash
# Post-setup hook: provisions the local Convex backend.
# Runs inside the cspace container as the dev user after workspace init.
# Uses docker exec (via mounted Docker socket) to reach sibling containers.
set -euo pipefail

CONVEX_CONTAINER="${CSPACE_CONTAINER_NAME}.convex"

# Clean up partial state from a previous failed run
sed -i '/^# Local Convex backend/d; /^CONVEX_SELF_HOSTED_URL=/d; /^CONVEX_SELF_HOSTED_ADMIN_KEY=/d; /^VITE_CONVEX_URL=/d' /workspace/.env.local 2>/dev/null || true

# Comment out cloud deployment vars in all env files and unset from current
# environment to avoid conflicts with the local self-hosted backend.
sed -i 's/^CONVEX_DEPLOYMENT=/#&/' /workspace/.env /workspace/.env.local 2>/dev/null || true
sed -i 's/^CONVEX_DEPLOY_KEY=/#&/' /workspace/.env /workspace/.env.local 2>/dev/null || true
unset CONVEX_DEPLOYMENT CONVEX_DEPLOY_KEY

# Wait for backend to be healthy
echo "Waiting for Convex backend..."
for i in $(seq 1 30); do
    if docker exec "$CONVEX_CONTAINER" curl -sf http://localhost:3210/version >/dev/null 2>&1; then
        break
    fi
    [ "$i" -eq 30 ] && { echo "ERROR: Convex backend not healthy after 30s"; exit 1; }
    sleep 1
done

# Generate admin key
echo "Generating admin key..."
ADMIN_KEY=$(docker exec "$CONVEX_CONTAINER" ./generate_admin_key.sh | grep -v '^$' | tail -1)
[ -z "$ADMIN_KEY" ] && { echo "ERROR: Failed to generate admin key"; exit 1; }

# Write self-hosted config to .env.local
CONVEX_PUBLIC_URL="http://convex.${CSPACE_INSTANCE_NAME:-$(hostname)}.${CSPACE_PROJECT_NAME:-cspace}.cspace.local"

printf '\n# Local Convex backend (auto-generated by post-setup.sh)\nCONVEX_SELF_HOSTED_URL=http://%s:3210\nCONVEX_SELF_HOSTED_ADMIN_KEY=%s\nVITE_CONVEX_URL=%s\n' "$CONVEX_CONTAINER" "$ADMIN_KEY" "$CONVEX_PUBLIC_URL" \
    >> /workspace/.env.local

# Backup admin key to home dir (survives worktree switches and .env.local clobbers)
printf 'CONVEX_SELF_HOSTED_URL=http://%s:3210\nCONVEX_SELF_HOSTED_ADMIN_KEY=%s\n' "$CONVEX_CONTAINER" "$ADMIN_KEY" \
    > "$HOME/.convex-env"

# Push schema and functions to local backend
echo "Pushing schema to local backend..."
mkdir -p /workspace/.convex-tmp
cd /workspace && CONVEX_TMPDIR=/workspace/.convex-tmp pnpm exec convex dev --once --typecheck disable

# Generate RSA key pair for @convex-dev/auth
echo "Generating auth keys..."
node -e "
  const { generateKeyPairSync, createPublicKey } = require('crypto');
  const { privateKey, publicKey } = generateKeyPairSync('rsa', {
    modulusLength: 2048,
    publicKeyEncoding: { type: 'spki', format: 'pem' },
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
  });
  const jwk = createPublicKey(publicKey).export({ format: 'jwk' });
  jwk.kid = 'local-dev';
  jwk.use = 'sig';
  jwk.alg = 'RS256';
  require('fs').writeFileSync('/tmp/jwt_private_key.pem', privateKey);
  require('fs').writeFileSync('/tmp/jwks.json', JSON.stringify({ keys: [jwk] }));
"
cd /workspace && pnpm exec convex env set -- JWT_PRIVATE_KEY "$(cat /tmp/jwt_private_key.pem)"
cd /workspace && pnpm exec convex env set JWKS "$(cat /tmp/jwks.json)"
rm -f /tmp/jwt_private_key.pem /tmp/jwks.json
echo "Auth keys configured."

# TODO: Set additional Convex environment variables as needed.
# Example:
#   cd /workspace && pnpm exec convex env set MY_API_KEY "$MY_API_KEY"

# TODO: Seed initial data.
# Example:
#   cd /workspace && pnpm exec convex run seeds/initial:seed

# Mark convex-init as fully complete
touch /workspace/.convex-init-done

echo ""
echo "Local Convex backend ready!"
